include:
  - project: 'infrastructure/developer-productivity/pipeline-template-definitions'
    file: 'build.yml'
  - project: 'infrastructure/developer-productivity/pipeline-template-definitions'
    file: 'deploy.yml'

stages:
  - build
  - deploy_sandbox

build_image:
  extends: .build_image

deploy_sandbox_us:
  before_script:
    - export
    - sh bin/generate_chart.sh
  extends: .deploy_sandbox_us
  when: on_success
